import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/index.module.scss';
import Navbar from '../components/navbar';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Showcase Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.helloworld}>
        This page is still a work in progress...
      </main>
    </div>
  )
}

export default Home
